---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dlotonil/public_html/
    - /bin/cp ./* $DEPLOYPATH/
    - /bin/cp -r ./assets $DEPLOYPATH/assets
    - /bin/cp ./core/* $DEPLOYPATH/core/
    - /bin/cp -r ./app $DEPLOYPATH/app
    - /bin/cp -r ./bootstrap $DEPLOYPATH/bootstrap
    - /bin/cp -r ./config $DEPLOYPATH/config
    - /bin/cp -r ./database $DEPLOYPATH/database
    - /bin/cp -r ./lang $DEPLOYPATH/lang
    - /bin/cp -r ./resources $DEPLOYPATH/resources
    - /bin/cp -r ./routes $DEPLOYPATH/routes
    - /bin/cp -r ./tests $DEPLOYPATH/tests
    - /bin/rm -rf $DEPLOYPATH/vendor
    - /bin/composer update --no-dev --optimize-autoloader
    - /bin/php artisan optimize:clear