---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dlotonil/public_html/
    - /bin/cp ./* $DEPLOYPATH/
    - /bin/cp -r ./assets $DEPLOYPATH/assets
    - /bin/cp ./core/* $DEPLOYPATH/core/
    - /bin/cp -r ./core/app $DEPLOYPATH/core/app
    - /bin/cp -r ./core/bootstrap $DEPLOYPATH/core/bootstrap
    - /bin/cp -r ./core/config $DEPLOYPATH/core/config
    - /bin/cp -r ./core/database $DEPLOYPATH/core/database
    - /bin/cp -r ./core/lang $DEPLOYPATH/core/lang
    - /bin/cp -r ./core/resources $DEPLOYPATH/core/resources
    - /bin/cp -r ./core/routes $DEPLOYPATH/core/routes
    - /bin/cp -r ./core/tests $DEPLOYPATH/core/tests
#    - /bin/composer install --no-dev --optimize-autoloader
 #   - /bin/php artisan optimize:clear